example <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 4, ncol = 2)
view(example)
library(datasets)
data(iris)
summary(iris)
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicFeatures")
library(devtools)
install_github("author/package")
update.packages()
browseVignettes()``
browseVignettes("ggplot2")
library(KernSmooth)
sessionInfo()